[build]
builder = "nixpacks"
buildCommand = "npm run setup && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
install-cmd = "npm install -g typescript && npm run setup"
